<?php


$title = "P H P  N e w s  P o s t e r";

$table_image = "arr";
$table_bgcolor = "#000000";
$table_cellpadding = "5";
$table_cellspacing = "0";
$table_width = "600";
$table_height = "*";
$table_border = "1";
$td_header_valign = "top";
$td_message_valign = "top";
$td_width = "50%";
$td_header_color = "#eeee00";
$table_message_color = "#eeeeee";

$post_header_color = "#ff0000";
$post_header_size = "2";
$post_header_face = "arial";
$post_text_color = "#0000ff";
$post_text_size = "1";
$post_text_face = "arial";

$news = "admin";
$poster = "password";
$email = "webmaster@yoursite.com";

?>