<?php


$language = array();


$language['username'] = "Name";
$language['password'] = "Password";
$language['thelogin'] = "Login";


$language['Welcome'] = "Welcome";
$language['Guestbook'] = "Guestbook";
$language['post'] = "Post New message";
$language['edit'] = "Edit";
$language['postit'] = "Post message";
$language['poster'] = "Poster";
$language['message'] = "Message";
$language['date'] = "Date";
$language['by'] = "By";
$language['noposts'] = "Sorry no topics in this Guestbook.";
$language['backtobook'] = "Back to Guestbook";


$language['requiredinfo']  = "Required Infomation";
$language['optionalinfo'] = "Optional Personal Infomation";
$language['interests']  = "Interests";
$language['contact']  = "Contact";
$language['theemail']  = "Email";
$language['age'] = "Age";
$language['from'] = "Country";
$language['homepage']  = "Homepage";
$language['icq'] = "ICQ";
$language['msnm']  = "MSN Messenger";
$language['aimm'] = "AIM";


$language['send'] = "Send";
$language['your'] = "Your";
$language['successful'] = "Successfully deleted";
$language['sent'] = "sent";
$language['reply'] = "Reply";
$language['recipicant'] = "Recipicant";


$language['lostpass']  = "Lost Password";
$language['emailaddress']  = "E-Mail Address";
$language['getnew'] = "Get New Password";


$language['aicqmsg']  = "a icq message";
$language['go']  = "Go!";

