<?php

// general colours etc
$title = "PHP News Poster";
$table_image = "arr";
$table_bgcolor = "#000000";
$table_cellpadding = "5";
$table_cellspacing = "0";
$table_width = "600";
$table_height = "*";
$table_border = "1";
$td_header_valign = "top";
$td_message_valign = "top";
$td_width = "50%";
$td_header_color = "#eeee00";
$table_message_color = "#eeeeee";
$post_header_color = "#ff0000";
$post_header_size = "2";
$post_header_face = "arial";
$post_text_color = "#0000ff";
$post_text_size = "1";
$post_text_face = "arial";

// Initial Administrator Details

$news = "webmaster";
$poster = "5f4dcc3b5aa765d61d8327deb882cf99";
$email = "webmaster@yoursite.com";
$posted = "this is your first news message";
$postedtime = "26 march 1984";

// Data base Information

$dbhost = "localhost";
$dbuser = "xdwebn";
$dbpasswd = "elbicid";
$dbname = "xdwebdata";

// cookie info you have to edit
// make user its .yourdomain.com 
// if your getting problems with the cookie try like .domain.com/~yourarea/
// or .yourarea.domain.com
// the key is fiddle with it

$cookie_domain = '.xdweb.net/';  


// dont edit below this point unless your trying to fuck shit up lol

$ok ="<img src='images/ok.gif' border='0'>";
$notok ="<img src='images/notok.gif' border='0'>";


?>